name: Integration Test
on: [ push ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Import Vault Secrets
        id: secrets
        uses: safe2008/vault-actions@main
        with:
          url: ${{ secrets.VAULT_ADDR }}
          token: ${{ secrets.VAULT_TOKEN }}
          secrets: argocd/data/token admin | ARGOCD_TOKEN ;

      - name: Self test
        id: selftest
        uses: safe2008/argocd-app-actions@main
        with:
          address: ${{ secrets.ARGOCD_ADDR }}
          token: ${{ steps.secrets.outputs.ARGOCD_TOKEN }}
          insecure: false
          appName: horusec-platform
